---
title: Diepzee-sushi
hero_image: images/banner.png
description: Maak een leuk spel in je eerste Scratch-programma!
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: animals, humour, outdoors, games
technologies: scratch
site_areas: coderdojo
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
    completion: engaged
  - 
    title: Opstarten
  - 
    title: Toevoegen en verwijderen van codeblokken
  - 
    title: Het opzetten van de scene
  - 
    title: Beweeg dingen in het rond
  - 
    title: Alle sprites
  - 
    title: Vis op afstand bestuurbaar
  - 
    title: Vissen!
    completion: internal
  - 
    title: Score bijhouden
  - 
    title: 'Uitdaging: het spel winnen'
    challenge: true
