---
title: गहरे समुद्र में सुशी
hero_image: images/banner.png
description: अपने पहले स्क्रैच कार्यक्रम में एक मजेदार गेम बनाएं!
theme: नारंगी #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, डिजाइन -0, प्रोग्रामिंग -1, फिजिकल-कम्प -0, निर्माण -0, समुदाय -0
interests: जानवर, हास्य, सड़क पर, खेल
technologies: scratch
site_areas: coderdojo
software: खरोंच
version: 4.0.0
last_tested: 2017-01-01
steps:
  - 
    title: भूमिका
  - 
    title: स्थापित हो रही है
  - 
    title: कोड ब्लॉक जोड़ना और निकालना
  - 
    title: दृश्य की स्थापना
  - 
    title: चीजों को इधर-उधर करना
  - 
    title: सभी स्प्राइट्स
  - 
    title: रिमोट-कंट्रोल मछली
  - 
    title: मछली पकड़ने
  - 
    title: हिसाब रखा
  - 
    title: "चुनौती: खेल जीतना"
    challenge: true
