---
title: Beginner Scratch Sushi Cards
hero_image: images/banner.png
description: Make a fun game in your first Scratch program!
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: animals, humour, outdoors, games
technologies: scratch
site_areas: coderdojo
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Getting set up
  - 
    title: Adding and removing code blocks
  - 
    title: Setting the scene
  - 
    title: Moving things around
  - 
    title: All the sprites
  - 
    title: Remote-control fish
  - 
    title: Fishing!
  - 
    title: Keeping score
  - 
    title: "Challenge: winning the game"
    challenge: true
