---
title: Sushi de mar profundo
hero_image: images/banner.png
description: '¡Crea un juego divertido en tu primer programa Scratch!'
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: animals, humour, outdoors, games
technologies: scratch
site_areas: coderdojo
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Preparación
  - 
    title: Agregar y eliminar bloques de código
    completion:
      - engaged
  - 
    title: Preparando la escena
  - 
    title: Moviendo bloques
  - 
    title: Todos los objetos
  - 
    title: Control remoto del pez
  - 
    title: '¡Pescando!'
  - 
    title: Guardando la puntuación
    completion:
      - internal
  - 
    title: 'Desafío: ganando el juego'
    challenge: true
