---
title: Tiefsee-Sushi
hero_image: images/banner.png
description: Mach ein lustiges Spiel in deinem ersten Scratch-Programm!
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: animals, humour, outdoors, games
technologies: scratch
site_areas: Coderdojo
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
- title: Einleitung
- title: Erste Schritte
- title: Codeblöcke hinzufügen und entfernen
  completion:
  - engaged
- title: Einrichten der Szene
- title: Dinge bewegen
- title: Alle Figuren
- title: Ferngesteuerte Fische
- title: Angeln!
- title: Mitzählen
  completion:
  - internal
- title: 'Herausforderung: das Spiel gewinnen'
  challenge: true
