---
title: Sushi în ape adânci
hero_image: images/banner.png
description: Creează un joc distractiv cu primul tău program Scratch!
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: animals, humour, outdoors, games
technologies: scratch
site_areas: coderdojo
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
- title: Introducere
  completion: engaged
- title: Pregătire
- title: Adăugarea și ștergerea blocurilor de cod
- title: Pregătirea scenei
- title: Mișcarea elementelor
- title: Toate personajele
- title: Peștele care se mișcă singur
- title: La pescuit!
  completion: internal
- title: Memorarea scorului
- title: 'Provocare: câștigarea jocului'
  challenge: true
