---
title: Sushi do fundo do mar
hero_image: imagens/banner.png
description: Faça um jogo divertido no seu primeiro programa Scratch!
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: animais, humor, ar livre, jogos
technologies: scratch
site_areas: coderdojo
software: scratch
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: Introdução
  - 
    title: Preparando
  - 
    title: Adicionando e removendo blocos de código
    completion:
      - engaged
  - 
    title: Preparando o cenário
  - 
    title: Movendo as coisas
  - 
    title: Todos os atores
  - 
    title: Peixe de controle remoto
  - 
    title: Pescando!
  - 
    title: Mantendo a pontuação
    completion:
      - internal
  - 
    title: 'Desafio: vencer o jogo'
    challenge: true
