---
title: Sushi de mar profundo
hero_image: images/banner.png
description: '¡Crea un juego divertido en tu primer programa Scratch!'
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: animals, humour, outdoors, games
technologies: scratch
site_areas: coderdojo
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
    completion: engaged
  - 
    title: Preparativos
  - 
    title: Agregando y eliminando bloques de codigo
  - 
    title: Configurando al escena
  - 
    title: Moviendo las cosas alrededor
  - 
    title: Todos los objetos
  - 
    title: Control remoto del pez
  - 
    title: '¡Pescando!'
    completion: internal
  - 
    title: Guardando la puntuación
  - 
    title: 'Desafío: Ganar el juego'
    challenge: true
