---
title: Deep sea sushi
hero_image: images/banner.png
description: اصنع لعبة ممتعة في اول برنامج Scratch خاص بك!
theme: orange #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: animals, humour, outdoors, games
technologies: scratch
site_areas: coderdojo
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
  - 
    title: المقدمة
  - 
    title: هيا بنا لنبدأ
  - 
    title: إضافة وإزالة قوائم التعليمات البرمجية
  - 
    title: إعداد المشهد
  - 
    title: تحريك الأشياء في جميع الأنحاء
  - 
    title: كل الشخصيات
  - 
    title: الأسماك المتحكم بها عن بعد
  - 
    title: صيد السمك!
  - 
    title: حفظ النتيجة
  - 
    title: "التحدي: الفوز في اللعبة"
    challenge: true
