---
title: 깊은 바다 물고기
hero_image: images/banner.png
description: 첫 스크래치 프로그램에서 재미있는 게임을 만드십시오!
theme: orange #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: animals, humour, outdoors, games
technologies: 스크래치
site_areas: 코더 도조
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Getting set up
  - 
    title: Adding and removing code blocks
  - 
    title: Setting the scene
  - 
    title: Moving things around
  - 
    title: All the sprites
  - 
    title: Remote-control fish
  - 
    title: Fishing!
  - 
    title: Keeping score
  - 
    title: "Challenge: winning the game"
    challenge: true
