---
title: Sushi z głębin morskich
hero_image: images/banner.png
description: Zrób fajną grę w swoim pierwszym programie Scratch!
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: zwierzęta, humor, na zewnątrz, gry
technologies: scratch
site_areas: coderdojo
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
    completion: engaged
  - 
    title: Przygotowanie do pracy
  - 
    title: Dodawanie i usuwanie bloków kodu
  - 
    title: Ustawianie sceny
  - 
    title: Poruszanie rzeczy
  - 
    title: Wszystkie duszki
  - 
    title: Ryby zdalnie sterowane
  - 
    title: Wędkarstwo!
    completion: internal
  - 
    title: Zachowując wynik
  - 
    title: 'Wyzwanie: wygranie gry'
    challenge: true
