---
title: Sushi z głębin morskich
hero_image: images/banner.png
description: Zrób fajną grę w swoim pierwszym programie Scratch!
theme: orange #possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: animals, humour, outdoors, games
technologies: scratch
site_areas: coderdojo
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
  - title: Wprowadzenie
  - title: Przygotowanie do pracy
  - title: Dodawanie i usuwanie bloków kodu
  - title: Ustawianie sceny
  - title: Poruszanie rzeczami
  - title: Wszystkie duszki
  - title: Ryby zdalnie sterowane
  - title: Złap rybę!
  - title: Zapamiętywanie wyniku
  - title: "Wyzwanie: wygranie gry"
    challenge: true
