---
title: Sushi del mare profondo
hero_image: images/banner.png
description: Crea un gioco divertente nel tuo primo programma di Scratch!
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: animals, humour, outdoors, games
technologies: scratch
site_areas: coderdojo
software: scratch
version: 4.0.0
last_tested: 2017-01-01
steps:
  - 
    title: Introduzione
  - 
    title: Prepararsi
  - 
    title: Aggiunta e rimozione di blocchi di codice
  - 
    title: Organizzare la scena
  - 
    title: Spostare le cose
  - 
    title: Tutti gli sprite
  - 
    title: Pesce telecomandato
  - 
    title: A pesca!
  - 
    title: Tenere il punteggio
  - 
    title: "Sfida: vincere la partita"
    challenge: true
